[tasks.precommit]
run = [
  "./build.sh",
  "npm run format",
  "npm install",
  "composer install",
  "./vendor/bin/php-cs-fixer fix",
]

[tasks.phpstan]
run = ["./vendor/bin/phpstan --memory-limit=-1"]
