---
name: Test and lint code
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['20']
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: setup-php/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
      # We do not actually care about the package version, since we do not rely on any of them during production.
      - name: Update lockfile
        run: composer update
      - name: Install PHP dependencies
        run: composer install
      - name: Check PHP for lint errors
        run: ./vendor/bin/php-cs-fixer check
        continue-on-error: true
